# to give information about the simulations that we are running

[simulation]
input_data = "input_data/"
profiles_type = "ADJACENT"
# possibilities: "DISTANT", "ADJACENT", "MIXED", "HALFMIXED"
n_runs = 10

[clustering]
use_ratio = false
heuristic_distance = false

